config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  namespace :api, defaults: {format: :json } do
    namespace :v1 do
      resources :expenses, except: [:new, :edit]
    end
  end

  get 'dashboard', to: 'dashboard#index'
  get 'category', to: 'dashboard#category'
  get 'months', to: 'dashboard#last_six_months'
  get 'daily', to: 'dashboard#by_day'
  get 'accumulated', to: 'dashboard#accumulated'
  resources :expenses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :expenses
end

app/models/expense.rb
# == Schema Information
#
# Table name: expenses
#
#  id          :integer          not null, primary key
#  date        :date
#  concept     :string
#  amount      :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  type_id     :integer
#

class Expense < ApplicationRecord
  belongs_to :category
  belongs_to :type
  validates :type_id, :category_id, :date, :concept, :amount, presence: true
  validates :amount, numericality: true

  scope :by_category, ->(category) { where(category_id: category) }
  scope :by_type, ->(type) { where(type_id: type) }
  scope :by_month, ->(date) { where(date: "#{date}-01".to_date.."#{date}-01".to_date.end_of_month) }

  def self.categories
    expenses = Expense.where(date: Time.now.beginning_of_month..Time.now.end_of_month)
    cat1 = cat2 = cat3 = cat4 = cat5 = cat6 = cat7 = cat8 = 0
    expenses.each do |expense|
      if expense.category_id == 1
        cat1 += expense.amount
      elsif expense.category_id == 2
        cat2 += expense.amount
      elsif expense.category_id == 3
        cat3 += expense.amount
      elsif expense.category_id == 4
        cat4 += expense.amount
      elsif expense.category_id == 5
        cat5 += expense.amount
      elsif expense.category_id == 6
        cat6 += expense.amount
      elsif expense.category_id == 7
        cat7 += expense.amount
      elsif expense.category_id == 8
        cat8 += expense.amount
      end
    end
    by_category = [[1,cat1], [2, cat2], [3, cat3], [4, cat4], [5, cat5], [6, cat6], [7, cat7], [8, cat8]]
  end

  def self.last_six_months
    by_month = []
    6.times do |i|
      type1 = type2 = type3 = type4 = 0
      month = (Time.now.beginning_of_month - i.month).strftime("%b-%Y")
      monthly_expenses = Expense.where(date:(Time.now.beginning_of_month - i.month)..(Time.now.end_of_month-i.month))

      monthly_expenses.each do |expense|
        if expense.type_id == 1
          type1 += expense.amount
        elsif expense.type_id == 2
          type2 += expense.amount
        elsif expense.type_id == 3
          type3 += expense.amount
        elsif expense.type_id == 4
          type4 += expense.amount
        end
      end

      by_month[i] = { purchase: type1, withdrawal: type2, transfer: type3, payment: type4, month: month }
    end
    by_month
  end

  def self.daily
    daily = []
    d = Time.now.day
    m = Time.now.month
    y = Time.now.year

    (0...d).each do |i|
      daily[i] = {expense: Expense.where(date:("#{y}-#{m}-#{d-i}")).sum(:amount), day: d-i}
    end
    daily
  end

  def self.accumulated
    last_m = 1.month.ago.month
    last_y = 1.month.ago.year
    accumulated_actual = 0
    accumulated_last = 0
    total = []

    (1..Time.now.end_of_month.day).each do |i|
      if i <= Time.now.day
        accumulated_actual += Expense.where(date:("#{Time.now.year}-#{Time.now.month}-#{i}")).sum(:amount)
      else
        accumulated_actual=0
      end
      accumulated_last += Expense.where(date:("#{last_y}-#{last_m}-#{i}")).sum(:amount)
      total[i-1] = {last: accumulated_last , actual: accumulated_actual,  day:i}
    end
    total
  end

end

app/models/type.rb
# == Schema Information
#
# Table name: types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Type < ApplicationRecord
  has_many :expenses
end

app/controllers/api/v1/expenses_controller.rb
module Api
  module V1
    class ExpensesController < ApplicationController
       protect_from_forgery with: :null_session
      def index
        expenses = Expense.order("date ASC")
        expenses = expenses.by_month(params[:date]) if params[:date]
        expenses = expenses.by_type(params[:type_id]) if params[:type_id]
        expenses = expenses.by_category(params[:category_id]) if params[:category_id]
        render json: expenses
      end

      def show
        expense = Expense.find(params[:id])
        render json: expense
      end

      def create
        expense = Expense.new(expense_params)
        if expense.save
          render json: expense, status: 201
        else
          render json: {errors: expense.errors}, status: 422
        end
      end

      def update
        expense = Expense.find(params[:id])
        if expense.update(expense_params)
          render json: expense, status: 200
        else
          render json: {errors: expense.errors}, status: 422
        end
      end

      def destroy
        expense = Expense.find(params[:id])
        expense.destroy
        head :no_content
      end

      private
        def expense_params
          params.require(:expense).permit(:type_id, :date, :concept, :category_id, :amount)
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @tab = :dashboard
    @today = Expense.where("date = ?", Date.today).sum(:amount)
    @yesterday = Expense.where("date = ?", Date.yesterday).sum(:amount)
    @this_month = Expense.where(date: Time.now.beginning_of_month..Time.now.end_of_month).sum(:amount)
    @last_month = Expense.where(date: (Time.now.beginning_of_month - 1.month)..(Time.now.end_of_month-1.month)).sum(:amount)
  end

  def category
    by_category = Expense.categories
    render json: by_category
  end

  def last_six_months
    by_month = Expense.last_six_months
    render json: by_month
  end

  def by_day
    daily = Expense.daily
    render json: daily
  end

  def accumulated
    total = Expense.accumulated
    render json: total
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :filter
  def filter
    @expenses = Expense.order("date ASC")
    if params[:date]
      @expenses = @expenses.by_month(params[:date])
    else
      @expenses = @expenses.by_month("#{Date.today.year}-#{Date.today.month}")
    end
    @expenses = @expenses.by_type(params[:type_id]) if params[:type_id]
    @expenses = @expenses.by_category(params[:category_id]) if params[:category_id]

  end

  def index
    @tab = :expenses
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def show
    @expense = Expense.find(params[:id])
  end

  def new
    @expense = Expense.new
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.save
    respond_to do |format|
      format.js
    end
  end

  def update
    @expense = Expense.find(params[:id])
    @expense.update(expense_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: "The #{@expense.type.name} #{@expense.concept} for #{@expense.amount} on #{@expense.date} was successfully delete." }
      format.json { head :no_content }
    end
  end

  private
    def expense_params
      params.require(:expense).permit(:type_id, :date, :concept, :category_id, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def self.last_twelve_months
    (0..11).map do |i|
      "#{i.month.ago.year}-#{i.month.ago.month}"
    end
  end
end

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="total-box col-md-3">
      <div class="value">
        <%= Money.new(@today*100, "USD").format(:no_cents =>true) %>
      </div>
      <span>TODAY</span>
    </div>
    <div class="total-box col-md-3">
      <div class="value">
        <%= Money.new(@yesterday*100, "USD").format(:no_cents =>true ) %>
      </div>
      <span>YESTERDAY</span>
    </div>
    <div class="total-box col-md-3">
      <div class="value">
        <%= Money.new(@this_month*100, "USD").format(:no_cents =>true) %>
      </div>
      <span>THIS MONTH</span>
    </div>
    <div class="total-box col-md-3">
      <div class="value">
        <%= Money.new(@last_month*100, "USD").format(:no_cents =>true ) %>
      </div>
      <span>LAST MONTH</span>
    </div>
  </div>


  <div class="row" style="margin-top: 40px;">
    <div class="box col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">Last 6 months</div>
        <div class="panel-body">
          <div id="last-six-month-expenses-chart" style="height: 250px;"></div>


        </div>
      </div>
    </div>
    <div class="box col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">By Day</div>
        <div class="panel-body">
          <div id="daily-expenses-chart" style="height: 250px;"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="row" style="margin-top: 10px;">
    <div class="box col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">By Category</div>
        <div class="panel-body">
          <div id="category-chart" style="height: 250px;"></div>
        </div>
      </div>
    </div>
    <div class=" box col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">Accumulated</div>
        <div class="panel-body">
          <div id="month-acc" style="height: 250px;"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/expenses/_alert.html.erb
<div class="alert alert-success alert-dismissible alert-growl" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= message.html_safe %>
</div>

app/views/expenses/_filtered_expenses.html.erb
<% @expenses.each do |expense| %>
<tr>
  <td class="date">
    <div class="day"><%=expense.date.strftime("%d")%></div>
    <div class="month"><%=expense.date.strftime("%B")%></div>
  </td>
  <td>
    <div>
      <span class="type"><%=expense.type.name%></span>
    </div>
    <div>
      <span class="concept"><%=expense.concept%></span>
    </div>
  </td>
  <td class="category text-right"><%=expense.category.name%></td>
  <td class="text-right" style="width: 170px;">
    <div class="amount"><%=expense.amount%></div>
    <div class="actions">
      <%= link_to "<span class='glyphicon glyphicon-edit'></span>Edit".html_safe, edit_expense_path(expense), remote: true%>
      <%= link_to "<span class='glyphicon glyphicon-trash'></span>Delete".html_safe, expense, method: :delete, data: { confirm: "Are you sure to delete this expense?" } %>
      </div>
  </td>
</tr>
<% end %>

app/views/expenses/_filteredexpenses.html.erb
<% @expenses.each do |expense| %>
<tr>
  <td class="date">
    <div class="day"><%=expense.date.strftime("%d")%></div>
    <div class="month"><%=expense.date.strftime("%B")%></div>
  </td>
  <td>
    <div>
      <span class="type"><%=expense.type.name%></span>
    </div>
    <div>
      <span class="concept"><%=expense.concept%></span>
    </div>
  </td>
  <td class="category text-right"><%=expense.category.name%></td>
  <td class="text-right" style="width: 170px;">
    <div class="amount"><%=expense.amount%></div>
    <div class="actions">
      <%= link_to "<span class='glyphicon glyphicon-edit'></span>Edit".html_safe, edit_expense_path(expense), remote: true%>
      <%= link_to "<span class='glyphicon glyphicon-trash'></span>Delete".html_safe, expense, method: :delete, data: { confirm: "Are you sure to delete this expense?" } %>
      </div>
  </td>
</tr>
<% end %>

app/views/expenses/_form.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="expense-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <%= form_for @expense, remote: true do |f| %>
        <div class="modal-body">
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :type_id %><br>
                <%= f.select :type_id, options_from_collection_for_select(Type.all, "id", "name", @expense.type_id), class: "form-control" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :date %>
                <%= f.date_field :date, value:@expense.date ,id: :expense_date, class: "form-control"  %>
                <p class="help-block"></p>
              </div>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :concept %>
            <%= f.text_field :concept, id: :expense_concept, class: "form-control"  %>
            <p class="help-block"></p>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form">
                <%= f.label :category_id %>
                <%= f.select :category_id, options_from_collection_for_select(Category.all, "id", "name", @expense.category_id), class: "form-control" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :amount %>
                <%= f.number_field :amount, value: number_to_currency(f.object.amount.to_f, delimiter: '', unit: ''), step: :any, class: "form-control" %>
                <p class="help-block"></p>
              </div>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal" aria-label="Cerrar">Cancel</button>
          <%= f.submit id:"btn-submit",class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/expenses/_index_data_filtered.html.erb
<div class="row" style="margin-top: 10px;">
  <div class="summary-box col-md-4 text-center">
    <div class="summary-value"><%= Money.new(@expenses.sum(:amount)*100, "USD").format(:no_cents =>true) %></div>
    <div class="summary-label">Total</div>
  </diV>
  <div class="summary-box col-md-4 text-center">
    <div class="summary-value"><%=@expenses.count %></div>
    <div class="summary-label">Transactions</div>
  </div>
  <div class="summary-box col-md-4 text-center">
    <div class="summary-value"><%= Money.new(@expenses.average(:amount)*100, "USD").format(:no_cents =>true) %></div>
    <div class="summary-label">Average</div>
  </div>
</div>

app/views/expenses/_indexdatafiltered.html.erb
<div class="row" style="margin-top: 10px;">
  <div class="summary-box col-md-4 text-center">
    <div class="summary-value"><%= Money.new(@expenses.sum(:amount)*100, "USD").format(:no_cents =>true) %></div>
    <div class="summary-label">Total</div>
  </diV>
  <div class="summary-box col-md-4 text-center">
    <div class="summary-value"><%=@expenses.count %></div>
    <div class="summary-label">Transactions</div>
  </div>
  <div class="summary-box col-md-4 text-center">
    <div class="summary-value"><%= Money.new(@expenses.average(:amount)*100, "USD").format(:no_cents =>true) %></div>
    <div class="summary-label">Average</div>
  </div>
</div>

app/views/expenses/_update.js.erb
<% if @expense.valid? %>
  $('#expense-modal').modal('hide');
  $('table tbody').html(' <%= j render "filtered_expenses", expense: @expense %>');
  $('#index-values').html("<%= j render 'index_data_filtered' %>");
  $('body').append('<%= j render "alert", message: message %>')
<% else %>
  $('.help-error').remove();
  $('.form-group').removeClass('has-error');

  <% @expense.errors.each do |field, messages| %>
    $('#expense_<%= field %>').parent().addClass('has-error')
      .append('<span class="help-block help-error"><%= messages %></span>');
  <% end %>
<% end %>

app/views/expenses/create.js.erb
<%= render 'update', message: "The #{@expense.type.name} <strong>#{@expense.concept}</strong> for <strong>#{number_to_currency(@expense.amount)}</strong> on <strong>#{@expense.date}</strong> was created successfully!" %>

app/views/expenses/edit.js.erb
$('<%= j render "form", title: "Expense" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/expenses/index.html.erb
<div class="notice alert-growl alert alert-success alert-dismissible" role="alert" id="notice" style="display:none;">

</div>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h4 class="filter-header">Transaction Type <span>Choose to filter</span></h4>
      <div class="list-group filter-type">
        <li class="list-group-item" id="1">Purchase</li>
        <li class="list-group-item" id="2">Withdrawal</li>
        <li class="list-group-item" id="3">Transfer</li>
        <li class="list-group-item" id="4">Payment</li>
      </div>

      <h4 class="filter-header">Categoría <span>Choose to filter</span></h4>
      <div class="list-group filter-category">
        <li class="list-group-item" id="1">Restaurants</li>
        <li class="list-group-item" id="2">Gocery</li>
        <li class="list-group-item" id="3">Car</li>
        <li class="list-group-item" id="4">Services</li>
        <li class="list-group-item" id="5">Home</li>
        <li class="list-group-item" id="6">Education</li>
        <li class="list-group-item" id="7">Fun</li>
        <li class="list-group-item" id="8">Travel</li>
      </div>
    </div>

    <div class="col-md-9 index-data" >
      <div class="row" style="margin-top: 10px;" id="index-values">
        <div class="summary-box col-md-4 text-center">
          <div class="summary-value"><%= Money.new(@expenses.sum(:amount)*100, "USD").format(:no_cents =>true) if @expenses.exists?%></div>
          <div class="summary-label">Total</div>
        </diV>
        <div class="summary-box col-md-4 text-center">
          <div class="summary-value"><%=@expenses.count if @expenses.exists?%></div>
          <div class="summary-label">Transactions</div>
        </div>
        <div class="summary-box col-md-4 text-center">
          <div class="summary-value"><%= Money.new(@expenses.average(:amount)*100, "USD").format(:no_cents =>true) if @expenses.exists? %></div>
          <div class="summary-label">Average</div>
        </div>
      </div>

      <div class="row" style="margin-top: 20px;">
        <div class="col-md-12">
        <%= link_to '<span class="glyphicon glyphicon-plus"></span> New Expense'.html_safe, new_expense_path, remote: true, class: "btn btn-success" %>
          <h4 class="dropdown pull-right">
            <%= select("timer", "start", ExpensesHelper.last_twelve_months) %>
          </h4>
        </div>
      </div>

      <table id="expenses-table" class="table table-hover" style="margin-top: 20px;">
        <thead>
          <tr>
            <th class="text-center">Día</th>
            <th>Concepto</th>
            <th class="text-right">Categoría</th>
            <th class="text-right">Valor</th>
          </tr>
        </thead>
        <tbody>
          <% @expenses.each do |expense| %>
          <tr>
            <td class="date">
              <div class="day"><%=expense.date.strftime("%d")%></div>
              <div class="month"><%=expense.date.strftime("%B")%></div>
            </td>
            <td>
              <div>
                <span class="type"><%=expense.type.name%></span>
              </div>
              <div>
                <span class="concept"><%=expense.concept%></span>
              </div>
            </td>
            <td class="category text-right"><%=expense.category.name%></td>
            <td class="text-right" style="width: 170px;">
              <div class="amount"><%=expense.amount%></div>
              <div class="actions">
                <%= link_to "<span class='glyphicon glyphicon-edit'></span>Edit".html_safe, edit_expense_path(expense), remote: true%>
                <%= link_to "<span class='glyphicon glyphicon-trash'></span>Delete".html_safe, expense, method: :delete, data: { confirm: "Are you sure to delete this expense?" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/expenses/index.js.erb
$('tbody').html("<%= j render 'filtered_expenses' %>");
$('#index-values').html("<%= j render 'index_data_filtered' %>");

app/views/expenses/new.js.erb
$('<%= j render "form", title: "Expense" %>').modal();

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @expense.type.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Concept:</strong>
  <%= @expense.concept %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expense.category.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/update.js.erb
<%= render 'update', message: "The expense was updated successfully!" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expenses</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Expensify</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if @tab == :dashboard %>"><%= link_to "Dashboard", root_path %></li>
            <li class="<%= 'active' if @tab == :expenses %>"><%= link_to "Expenses", expenses_path %></li>
          </ul>
        </div>
      </div>
    </nav>
    <%if notice %>
      <div class="notice alert-growl alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <%if alert %>
      <div class="notice alert-growl alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>

    <!-- <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script> -->
    <script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js">
    </script>
    <% if Rails.env == "production"  %>
      <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-124047253-1']);
        _gaq.push(['_trackPageview']);
        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

      </script>
    <% end %>
  </body>
</html>